### ISSUE TITLE
performance of ANTsR with respect to ANTs

### ISSUE THREAD

**Issue by muratmaga** [ANTsX/ANTsR#197]
Hi,

I recently ran a test registering two large volumes using antsRegistrationSyN.sh and antsRegister on a vm with 44 vcpus

I specified 'CC' and 'SyN' for ANTsR explicitly and left everything else default. For the command line version everything was default. In both cases ITK_GLOBAL_NUMBER_OF_THREADS was set to 44, command line version that the -n 44 switch. R version took 10X longer than the shell script. 

Are there expected performance losses running registration through R? I didn't check the number of iterations to be run (assumed will be same between ANTsR and command line, but may not be true). Another issue is, this was run on a cloud VM, so it is possible that other things might be running when the R version was executing. I will try to repeat the test on a dedicated system, but meanwhile would like to know if performance loss is expected when things run through R.

**Comment by muschellij2** [comment]
I don't think they are the same defaults.   You can see the defaults in

Also, I think ANTsR may use ITK_GLOBAL_*DEFAULT*_NUMBER_OF_THREADS not
ITK_GLOBAL_NUMBER_OF_THREADS.

I'd recommend giving a MCWE (https://stackoverflow.com/help/mcve) for this
to actually debug.

John

**Comment by muratmaga** [comment]
Hi John,

Sorry, that was a typo in my end. It is indeed ITK_GLOBAL_*DEFAULT*_NUMBER_OF_THREADS for both. And ANTsR was indeed using the multiple threads.
I will prepare a sample dataset once retest on a dedicated system, and explicitly specifying the all parameters.

I just wanted to know if it is expected to get a performance hit running things through R and whether anyone have done a test of similar sorts.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by stnava** [comment]
not expected.  both antsr and antspy call the same code that is used in
ants - they are just wrappers.  as indicated by @muschellij2 , you would
have to explicitly set the parameters to be "the same".  no need to test
this on large 3D datasets;  small 2D examples would be sufficient to verify.


brian

**Comment by dorianps** [comment]
I used to do some comparisons like this. On some earlier versions of ANTsR
I had a similar impression that ANTsR was taking longer. But at some point
thing's got comparable. The engine for the registrations is exactly the
same (provided you have updated ANTs and ANTsR versions). I would say that
a maximum difference I would expect is 1hr in ants and 1hr20min in ANTsR,
but not 10 times more. This said, I remember there is a slight difference
in the number of iterations, sampling, or something else between
antsRegistrationSyN.sh and antsRegistration('SyNCC'). In my opinion,
however, the ANTsR output was slightly better than that from ANTs.

My advice is:
- Make sure you have updated ANTsR/ANTs
- Run examples on single core if possible.
- Make sure you are running typeofTransform = 'SyNCC. in ANTsR,
because  typeofTransform = 'SyN' is indeed a suboptimal version much faster.
- Check the parameters used by each routine. Here is the ANTsR:
https://github.com/ANTsX/ANTsRCore/blob/master/R/antsRegistration.R#L343-L368
and here is antsRegistrationSyN.sh (scattered in some lines):
https://github.com/ANTsX/ANTs/blob/master/Scripts/antsRegistrationSyN.sh#L428-L438
https://github.com/ANTsX/ANTs/blob/master/Scripts/antsRegistrationSyN.sh#L511-L515

One last thing would be to check whether the two software manage the memory
differently, but this might be unlikely to cause a problem in such a
powerful system as yours.

Dorian

**Comment by muratmaga** [comment]
Yeah I definitely prefer to work with ANTsR than ANTs for many reasons. Thanks for all the advice.
I will try sometime soon again.
M


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
