### ISSUE TITLE
Permute/flip axes

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTsR#215]
Hey @stnava ,

Just making sure I didn't overlook something but I can't seem to find an ANTsR equivalent of ``PermuteFlipImageOrientationAxes``.  If correct, would you welcome that in ANTsR or should I put it in ANTsRNet?

**Comment by stnava** [comment]
probably an antsr add as more a core tool.

code could be something like:

?aperm

​where you as.array(...) as.antsImage ... but not sure that would be the
same thing.

you could combine aperm with reflectImage  to do quite a bit/probably all
of ​PermuteFlipImageOrientationAxes

also - maybe a better name would be appropriate?


brian

**Comment by ntustison** [comment]
Ah, you're right---can totally do it with existing functionality.  Thanks.

**Comment by ntustison** [comment]
Hey Brian, just a quick follow-up---I actually just performed an offline reorientation to MNI using ``antsRegistration`` as you outlined in one of your emails.  Then I simply add that MNI reorientation transform to the template-based data augmentation step in the batch generator.

**Comment by dorianps** [comment]
I had a similar issue today, with images received from collaborators who use different software.  I went back to `reorientImage` in ANTsR, which seems the same as `PermuteFlipimageOrientationAxes` in ANTs. However, `reorientImage` fails with the error below, while `PermuteFlipimageOrientationAxes` worked in command line.

```
> ss.mri
antsImage
  Pixel Type          : float 
  Components Per Pixel: 1 
  Dimensions          : 256x256x208 
  Voxel Spacing       : 1.10156202316284x1.10156202316284x1.10000598430634 
  Origin              : 114.4006 -140.9999 140.9999 
  Direction           : 0 1 0 0 0 -1 -1 0 0 

> raw.mri
antsImage
  Pixel Type          : float 
  Components Per Pixel: 1 
  Dimensions          : 208x256x256 
  Voxel Spacing       : 1.09999847412109x1.1015625x1.1015625 
  Origin              : 121.3972 128.2914 -130.1355 
  Direction           : -1 0 0 0 -1 0 0 0 1 

> reorientImage(ss.mri, axis1 = c(2,0,1))
 det nan
 A_solution /tmp/RtmpkLy2dm/devtoolsac6344a19da/stnava-ITKR-805a390/src/itks/Modules/ThirdParty/VNL/src/vxl/core/vnl/algo/vnl_svd.hxx: suspicious return value (3) from SVDC
/tmp/RtmpkLy2dm/devtoolsac6344a19da/stnava-ITKR-805a390/src/itks/Modules/ThirdParty/VNL/src/vxl/core/vnl/algo/vnl_svd.hxx: M is 3x3
M = [ ...
            -nan             -nan             -nan 
            -nan             -nan             -nan 
            -nan             -nan             -nan  ]

nan nan nan 
nan nan nan 
nan nan nan 

$reoimg
antsImage
  Pixel Type          : float 
  Components Per Pixel: 1 
  Dimensions          : 256x256x208 
  Voxel Spacing       : 1.10156202316284x1.10156202316284x1.10000598430634 
  Origin              : 114.4006 -140.9999 140.9999 
  Direction           : 0 1 0 0 0 -1 -1 0 0 


$txfn
[1] "/tmp/RtmpMXo6SB/file525a1b24e017.mat"
````

I found similar to @ntustison  by using `antsRegistration(typeofTransform = 'Translation')` followed by `antsApplyTransforms(interpolator = 'NearestNeighbor')`. The two images are now in the same space, turns out one of the images is bias corrected, so I don't have two identical images as I was expecting. But I have two more question here:
1. Should `reorientImage` in ANTsR be working the same as `PermuteFlipimageOrientationAxes` in ANTs?
2. I was hoping to avoid loosing time with `antsRegistration` and find exactly the kind of transformation required to move things from one space to the other, but so far can't find the translation/permutation/flip I need to apply. What's your advice here, shall I simply use `antsRegistration` or can I find the transformations from the existing parameters of the above images. In ITKsnap, the two images are oriented correctly but with a slight displacement, while in ANTsr::plot.antsimage they are oriented differently (as expected from the headers).

**Comment by stnava** [comment]
1.  `reorientImage` is not the same thing as `permute...` see
```
img=antsImageRead( getANTsRData('r16'))
 plot(reorientImage(img,c(0.5,0.5))$reoimg)
```
it aligns the principle axis of the image to the axis you specify on command line.   aperm gives you permutation options like permuteFlip....  i also doubt reorientImage "failed" since it's not doing much beyond what you tell it ( in your code, align to the axis defined by `c(2,0,1)` ...note it in 3D, you may also provide a 2nd axis.

2. `antsRegistration` would be the right call, assuming both spaces have correct anatomical coordinates.  you can do a very rapid transformation by modifying the parameters, assuming you are not trying to achieve perfection.

**Comment by dorianps** [comment]
thanks
