### ISSUE TITLE
Document how to add and test ANTsR code

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTsR#97]
I couldn't find any written instructions for contributing code. I made a start on a wiki page

https://github.com/stnava/ANTsR/wiki/Contributing-code-to-ANTsR

**Comment by dorianps** [comment]
Quick question:

Can one run roxygenize only on some functions/files or does it need to be the full ANTsR folder.

**Comment by stnava** [comment]
long overdue.

should note:

* using and reading travis output ... i.e. what we expect to see there

* writing documentation

* writing tests - importance of keeping tests fast (few seconds at most)

* writing examples - importance of keeping examples fast (few seconds at
most), otherwise use downturn

* contributing vignettes: why, how, speed ...

* coding style

* naming conventions



brian

**Comment by Tokazama** [comment]
This would be super helpful. If possible it would be nice to know how to imitate the travis checks beforehand to ensure a push is actually ready. 

@dorianps, I looked into performing a roxygenize on a single function/file but I'm pretty sure it needs to be the full ANTsR folder. My understanding is that its because roxygenize uses several elements of a full package directory. However, it shouldn't effect any functions or their respective documentation if you haven't changed them.

**Comment by stnava** [comment]
wickham's guide is solid

e.g.

http://r-pkgs.had.co.nz/tests.html



brian

**Comment by Tokazama** [comment]
I figured this was the best place to bring this up since it might help others that want to contribute code in the future. Right now I'm looking at implementing a method of fitting imaging data to a statistical model. More specifically I'd like to use C++ to speed the process up for larger data sets. I'm sure it's preferable to use ITK but some of ITK's dependencies might be better suited for some purely statistical solutions. I'm thinking specifically of VXL/VNL. Alternatively, it may be beneficial to just use something like RcppEigen given that it's already integrated into R and is used in packages suggested by ANTsR (i.e. lme4).

Ultimately, my question is this. What libraries/dependencies do you prefer to be used in contributing code? Additionally, do you prefer them to be used added as official dependencies if they aren't already or do you prefere scoping (misc3d::contour3d)?

**Comment by stnava** [comment]
we prefer scoping ... see the DESCRIPTION file and how we use `usePkg`
throughout.

ITK includes vxl/vnl as a dependency.  we also use Rcpp quite heavily.
 here is an example that maps R or Rcpp vectors to vnl data.

https://github.com/stnava/ANTsR/blob/master/src/sccaner.cpp#L138-L142


brian

**Comment by Tokazama** [comment]
I'd be happy to put together instructions on how to test packages before pull requests in the wiki since I need to figure it out anyway. I'm assuming the best approach would be to personally run the checks discussed in the 'ANTsR: towards CRAN & standardization of development' thread since those seem to be what travis checks uses.

**Comment by stnava** [comment]
that would be very welcome .... @bkandel recommended a pre-commit hook as a
reasonable option.  short story, running some variant of `R CMD build`
followed by `R CMD check` before committing is good practice.


brian

**Comment by Tokazama** [comment]
I had a quick novice question about how everyone is going about developing and testing their C++ code for ANTsR. From what I've seen a lot of people use Rcpp's `sourceCpp` command when testing stuff, but given ANTsR's dependence on cmake to compile things I'm assuming it wouldn't be as simple for code using ITK libraries. Do you typically use some other IDE to test C++ code or do you go through the whole `R CMD build ANTsR` each time you want to test code?

**Comment by stnava** [comment]
​my guess is that most of the ANTsR cpp code was tested outside of R ...
so, one would build a simple cpp ui and verify functionality (without
involving R).  then write the very simple R interface.​


brian

**Comment by cookpa** [comment]
This issue still a WIP but I added some more information to the Wiki page.
